[versions]
# libraries
junit = "4.13.2"
jackson-databind = "2.20.1"
jackson-module-kotlin = "2.20.1"
json-path = "2.10.0"
jmespath-jackson = "0.6.0"
datafaker = "2.5.3"

# plugins
changelog = "2.4.0"
intelliJPlatform = "2.10.5"
kotlin = "2.1.21"
kover = "0.9.3"
qodana = "2025.3.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
jacksonDatabind = {  group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson-databind" }
jacksonModuleKotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson-module-kotlin" }
jsonPath = { group = "com.jayway.jsonpath", name = "json-path", version.ref = "json-path" }
jmespathJackson = { group = "io.burt", name = "jmespath-jackson", version.ref = "jmespath-jackson" }
dataFaker = { group = "net.datafaker", name = "datafaker", version.ref = "datafaker" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }