[versions]
# libraries
junit = "4.13.2"
jackson-databind = "2.18.2"
jackson-module-kotlin = "2.18.2"
json-path = "2.9.0"

# plugins
changelog = "2.2.1"
intelliJPlatform = "2.3.0"
kotlin = "2.1.10"
kover = "0.8.3"
qodana = "2024.3.4"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
jacksonDatabind = {  group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson-databind" }
jacksonModuleKotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson-module-kotlin" }
jsonPath = { group = "com.jayway.jsonpath", name = "json-path", version.ref = "json-path" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }